### PR TITLE
for weaviate interactions

### PR DESCRIPTION
**Pull request by chfeng99**

### CODE REVIEW

**Review by segej87 — CHANGES_REQUESTED** [review]
@chfeng99 can you check the package configs (setup.py) and make sure all of the dependency packages are included? When I installed locally I got an error about not having weaviate package

**Comment by chfeng99** [comment]
> @chfeng99 can you check the package configs (setup.py) and make sure all of the dependency packages are included? When I installed locally I got an error about not having weaviate package

@segej87  It's done

**Comment by segej87** [comment]
> > @chfeng99 can you check the package configs (setup.py) and make sure all of the dependency packages are included? When I installed locally I got an error about not having weaviate package
> 
> @segej87 It's done

@chfeng99 I'm getting an error from pip: "Could not find a version that satisfies the requirement weaviate (from wpconnect) (from versions: none)". Are you sure you put the write PyPI package name?

**Review by segej87 — APPROVED** [review]
looks good

**Pull request merged**
